- hosts: localhost
  tasks:
    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        pkg:
          - git
          - ninja-build
          - gettext
          - cmake
          - curl
          - build-essential
    - name: Install tmux
      become: true
      ansible.builtin.package:
        name: tmux
        state: present
    - name: Checkout neovim
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim.git
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/neovim"
    - name: Build neovim
      make:
        chdir: "{{ lookup('ansible.builtin.env', 'HOME') }}/neovim"
        params:
          CMAKE_BUILD_TYPE: "RelWithDebInfo"
    - name: Install neovim
      become: true
      make:
        target: install
        chdir: "{{ lookup('ansible.builtin.env', 'HOME') }}/neovim"
